Repository HRocketRaccoon/HRaccoon-back, pull requests merged in 2024-05, with the labels that each got.

#1 [#1] 회원 관련 기능 구현
  build.gradle
  src/main/java/org/finalpjt/hraccoon/HraccoonApplication.java
  src/main/java/org/finalpjt/hraccoon/domain/user/constant/UserMessageConstants.java
  src/main/java/org/finalpjt/hraccoon/domain/user/constant/ValidationConstants.java
  src/main/java/org/finalpjt/hraccoon/domain/user/ctrl/UserController.java
  src/main/java/org/finalpjt/hraccoon/domain/user/data/dto/request/UserInfoRequest.java
  src/main/java/org/finalpjt/hraccoon/domain/user/data/dto/request/UserRequest.java
  src/main/java/org/finalpjt/hraccoon/domain/user/data/dto/response/UserResponse.java
  src/main/java/org/finalpjt/hraccoon/domain/user/data/entity/Ability.java
  src/main/java/org/finalpjt/hraccoon/domain/user/data/entity/User.java
  src/main/java/org/finalpjt/hraccoon/domain/user/data/entity/UserDetail.java
  src/main/java/org/finalpjt/hraccoon/domain/user/data/enums/Gender.java
  src/main/java/org/finalpjt/hraccoon/domain/user/data/enums/Role.java
  src/main/java/org/finalpjt/hraccoon/domain/user/repository/UserDetailRepository.java
  src/main/java/org/finalpjt/hraccoon/domain/user/repository/UserRepository.java
  src/main/java/org/finalpjt/hraccoon/domain/user/service/UserService.java
  src/main/java/org/finalpjt/hraccoon/global/abstracts/BaseTimeEntity.java
  src/main/java/org/finalpjt/hraccoon/global/exception/ResponseExceptionHandler.java
  src/main/resources/database/data.sql
Labels: enhancement, good first issue, Backend

#2 [#2] 직원 검색 및 조회 구현
  src/main/java/org/finalpjt/hraccoon/domain/approval/repository/ApprovalRepository.java
  src/main/java/org/finalpjt/hraccoon/domain/code/repository/CodeRepository.java
  src/main/java/org/finalpjt/hraccoon/domain/user/ctrl/UserController.java
  src/main/java/org/finalpjt/hraccoon/domain/user/data/dto/response/AbilityResponse.java
  src/main/java/org/finalpjt/hraccoon/domain/user/data/dto/response/ApprovalResponse.java
  src/main/java/org/finalpjt/hraccoon/domain/user/data/dto/response/UserSearchResponse.java
  src/main/java/org/finalpjt/hraccoon/domain/user/data/entity/Ability.java
  src/main/java/org/finalpjt/hraccoon/domain/user/repository/AbilityRepository.java
  src/main/java/org/finalpjt/hraccoon/domain/user/repository/UserRepository.java
  src/main/java/org/finalpjt/hraccoon/domain/user/sepecification/UserSpecification.java
  src/main/java/org/finalpjt/hraccoon/domain/user/service/UserService.java
  src/main/resources/database/data.sql
Labels: Backend

#4 [#4] 결재 상신 및 결재 목록 조회 구현
  src/main/java/org/finalpjt/hraccoon/domain/approval/constant/ApprovalMessageConstants.java
  src/main/java/org/finalpjt/hraccoon/domain/approval/ctrl/ApprovalController.java
  src/main/java/org/finalpjt/hraccoon/domain/approval/data/dto/request/ApprovalRequest.java
  src/main/java/org/finalpjt/hraccoon/domain/approval/data/dto/response/ApprovalResponse.java
  src/main/java/org/finalpjt/hraccoon/domain/approval/data/entity/Approval.java
  src/main/java/org/finalpjt/hraccoon/domain/approval/data/entity/ApprovalDetail.java
  src/main/java/org/finalpjt/hraccoon/domain/approval/data/enums/ApprovalStatus.java
  src/main/java/org/finalpjt/hraccoon/domain/approval/data/enums/ApprovalType.java
  src/main/java/org/finalpjt/hraccoon/domain/approval/repository/ApprovalRepository.java
  src/main/java/org/finalpjt/hraccoon/domain/approval/service/ApprovalService.java
  src/main/java/org/finalpjt/hraccoon/domain/user/ctrl/UserController.java
  src/main/java/org/finalpjt/hraccoon/domain/user/data/dto/response/ApprovalResponse.java
  src/main/java/org/finalpjt/hraccoon/domain/user/service/UserService.java
  src/main/resources/database/data.sql
Labels: enhancement, Backend
