Repository HRocketRaccoon/HRaccoon-back, pull requests merged in 2024-07, with the labels that each got.

#44 [BUILD] Deploy to main ver 0.0.4
  src/main/java/org/finalpjt/hraccoon/domain/user/data/dto/response/AdminUserResponse.java
  src/main/java/org/finalpjt/hraccoon/domain/user/service/AdminService.java
Labels: cicd

#46 [BUILD] Deploy to main ver 0.0.5
  src/main/java/org/finalpjt/hraccoon/domain/user/data/dto/request/AdminUserRequest.java
  src/main/java/org/finalpjt/hraccoon/domain/user/data/entity/User.java
Labels: cicd

#47 [#40] 근태 로직 및 배치 오류 수정
  src/main/java/org/finalpjt/hraccoon/batch/BatchConfig.java
  src/main/java/org/finalpjt/hraccoon/domain/attendance/ctrl/AttendanceController.java
  src/main/java/org/finalpjt/hraccoon/domain/attendance/data/dto/response/AttendacneMonthPercentResponseDTO.java
  src/main/java/org/finalpjt/hraccoon/domain/attendance/service/AttendanceService.java
Labels: bug, Backend, refactor

#49 [BUILD] Deploy to main ver 1.0.0
  src/main/java/org/finalpjt/hraccoon/batch/BatchConfig.java
  src/main/java/org/finalpjt/hraccoon/domain/approval/repository/ApprovalRepository.java
  src/main/java/org/finalpjt/hraccoon/domain/approval/service/ApprovalService.java
  src/main/java/org/finalpjt/hraccoon/domain/attendance/ctrl/AttendanceController.java
  src/main/java/org/finalpjt/hraccoon/domain/attendance/data/dto/response/AttendacneMonthPercentResponseDTO.java
  src/main/java/org/finalpjt/hraccoon/domain/attendance/repository/AttendanceRepository.java
  src/main/java/org/finalpjt/hraccoon/domain/attendance/service/AttendanceService.java
Labels: cicd

#50 [#42] 잔여 좌석 확인 api 생성
  src/main/java/org/finalpjt/hraccoon/domain/user/ctrl/UserController.java
  src/main/java/org/finalpjt/hraccoon/domain/user/data/dto/response/UserRemainVacationResponse.java
  src/main/java/org/finalpjt/hraccoon/domain/user/service/UserService.java
Labels: Backend

#52 [#44] 금주 근무시간 달성률 조회 로직 수정
  src/main/java/org/finalpjt/hraccoon/domain/attendance/service/AttendanceService.java
Labels: bug, Backend

#53 [BUILD] Deploy to main ver 1.0.0
  src/main/java/org/finalpjt/hraccoon/domain/attendance/data/entity/Attendance.java
  src/main/java/org/finalpjt/hraccoon/domain/attendance/service/AttendanceService.java
  src/main/java/org/finalpjt/hraccoon/domain/user/ctrl/UserController.java
  src/main/java/org/finalpjt/hraccoon/domain/user/data/dto/response/UserRemainVacationResponse.java
  src/main/java/org/finalpjt/hraccoon/domain/user/service/UserService.java
Labels: cicd

#55 [BUILD] Deploy to main ver 1.0.0
  src/main/java/org/finalpjt/hraccoon/domain/approval/repository/ApprovalRepository.java
  src/main/java/org/finalpjt/hraccoon/domain/approval/service/ApprovalService.java
  src/main/java/org/finalpjt/hraccoon/domain/attendance/service/AttendanceService.java
Labels: cicd

#57 [BUILD] Deploy to main ver 1.0.0
  src/main/java/org/finalpjt/hraccoon/domain/attendance/service/AttendanceService.java
Labels: cicd

#58 [#47] 일별 근무 시간 조회 로직 수정
  src/main/java/org/finalpjt/hraccoon/domain/attendance/service/AttendanceService.java
Labels: Backend
