Repository HRocketRaccoon/HRaccoon-back, pull requests merged in 2024-06, with the labels that each got.

#6 [#5] 잔여 좌석 조회 및 기존 코드 수정
  src/main/java/org/finalpjt/hraccoon/domain/approval/repository/ApprovalRepository.java
  src/main/java/org/finalpjt/hraccoon/domain/code/repository/CodeRepository.java
  src/main/java/org/finalpjt/hraccoon/domain/seat/ctrl/SeatController.java
  src/main/java/org/finalpjt/hraccoon/domain/seat/data/dto/SeatOfficeResponse.java
  src/main/java/org/finalpjt/hraccoon/domain/seat/repository/SeatStatusRepository.java
  src/main/java/org/finalpjt/hraccoon/domain/seat/service/SeatService.java
  src/main/java/org/finalpjt/hraccoon/domain/user/service/UserService.java
  src/main/java/org/finalpjt/hraccoon/global/config/WebConfig.java
  src/main/resources/application.yml
  src/main/resources/database/data.sql
Labels: enhancement, Backend

#8 [#7] 근태 관리 기능 구현
  build.gradle
  src/main/java/org/finalpjt/hraccoon/config/SecurityConfig.java
  src/main/java/org/finalpjt/hraccoon/domain/attendance/ctrl/AttendanceController.java
  src/main/java/org/finalpjt/hraccoon/domain/attendance/data/dto/response/AttendacneMonthPercentResponseDTO.java
  src/main/java/org/finalpjt/hraccoon/domain/attendance/data/dto/response/AttendacneWeekPercentResponseDTO.java
  src/main/java/org/finalpjt/hraccoon/domain/attendance/data/dto/response/AttendanceResponseDTO.java
  src/main/java/org/finalpjt/hraccoon/domain/attendance/data/entity/Attendance.java
  src/main/java/org/finalpjt/hraccoon/domain/attendance/data/entity/AttendanceDetail.java
  src/main/java/org/finalpjt/hraccoon/domain/attendance/repository/AttendanceRepository.java
  src/main/java/org/finalpjt/hraccoon/domain/attendance/service/AttendanceService.java
  src/main/java/org/finalpjt/hraccoon/domain/todo/ctrl/TodoController.java
  src/main/java/org/finalpjt/hraccoon/domain/todo/data/dto/TodoRequestDTO.java
  src/main/java/org/finalpjt/hraccoon/domain/todo/data/dto/TodoResponseDTO.java
  src/main/java/org/finalpjt/hraccoon/domain/todo/data/entity/Todo.java
  src/main/java/org/finalpjt/hraccoon/domain/todo/repository/TodoRepository.java
  src/main/java/org/finalpjt/hraccoon/domain/todo/service/TodoService.java
  src/main/java/org/finalpjt/hraccoon/domain/user/repository/UserRepository.java
Labels: enhancement, Backend

#9 [#8] 결재 목록 페이지네이션 추가
  src/main/java/org/finalpjt/hraccoon/domain/approval/ctrl/ApprovalController.java
  src/main/java/org/finalpjt/hraccoon/domain/approval/repository/ApprovalRepository.java
  src/main/java/org/finalpjt/hraccoon/domain/approval/service/ApprovalService.java
Labels: Backend

#11 feat: 결재자 리스트 저장 구현
  src/main/java/org/finalpjt/hraccoon/domain/approval/constant/ApprovalMessageConstants.java
  src/main/java/org/finalpjt/hraccoon/domain/approval/data/dto/request/ApprovalRequest.java
  src/main/java/org/finalpjt/hraccoon/domain/approval/service/ApprovalService.java
  src/main/java/org/finalpjt/hraccoon/domain/user/repository/UserRepository.java
Labels: Backend

#12 [#11] 데이터 삽입 sql문 추가 및 특정 좌석 직원 정보 조회 기능 구현
  src/main/java/org/finalpjt/hraccoon/config/SecurityConfig.java
  src/main/java/org/finalpjt/hraccoon/domain/seat/ctrl/SeatController.java
  src/main/java/org/finalpjt/hraccoon/domain/seat/data/dto/SeatOfficeFloorResponse.java
  src/main/java/org/finalpjt/hraccoon/domain/seat/data/dto/SeatUsingUserResponse.java
  src/main/java/org/finalpjt/hraccoon/domain/seat/repository/SeatStatusRepository.java
  src/main/java/org/finalpjt/hraccoon/domain/seat/service/SeatService.java
  src/main/resources/database/newdata.sql
Labels: enhancement, Backend

#13 [#12] 결재자 지정 저장 구현
  src/main/java/org/finalpjt/hraccoon/domain/approval/ctrl/ApprovalController.java
  src/main/java/org/finalpjt/hraccoon/domain/approval/data/dto/request/ApprovalRequest.java
  src/main/java/org/finalpjt/hraccoon/domain/approval/data/dto/response/ApprovalResponse.java
  src/main/java/org/finalpjt/hraccoon/domain/approval/data/entity/Approval.java
  src/main/java/org/finalpjt/hraccoon/domain/approval/data/entity/ApprovalDetail.java
  src/main/java/org/finalpjt/hraccoon/domain/approval/repository/ApprovalRepository.java
  src/main/java/org/finalpjt/hraccoon/domain/approval/service/ApprovalService.java
Labels: Backend

#14 [#13] 좌석 취소 오류 수정
  src/main/java/org/finalpjt/hraccoon/domain/approval/constant/ApprovalMessageConstants.java
  src/main/java/org/finalpjt/hraccoon/domain/approval/ctrl/ApprovalController.java
  src/main/java/org/finalpjt/hraccoon/domain/approval/data/dto/request/ApprovalResponseRequest.java
  src/main/java/org/finalpjt/hraccoon/domain/approval/data/dto/response/ApprovalResponse.java
  src/main/java/org/finalpjt/hraccoon/domain/approval/data/enums/ApprovalStatus.java
  src/main/java/org/finalpjt/hraccoon/domain/approval/repository/ApprovalRepository.java
  src/main/java/org/finalpjt/hraccoon/domain/approval/service/ApprovalService.java
  src/main/java/org/finalpjt/hraccoon/domain/seat/data/entity/SeatStatus.java
  src/main/java/org/finalpjt/hraccoon/domain/seat/service/SeatService.java
  src/main/resources/database/init-data.sql
Labels: Backend

#16 [#14] 결재 엔티티 수정, builder 패턴 적용
  src/main/java/org/finalpjt/hraccoon/domain/approval/data/dto/request/ApprovalRequest.java
  src/main/java/org/finalpjt/hraccoon/domain/approval/data/dto/response/ApprovalResponse.java
  src/main/java/org/finalpjt/hraccoon/domain/approval/data/entity/Approval.java
  src/main/java/org/finalpjt/hraccoon/domain/approval/data/entity/ApprovalDetail.java
  src/main/java/org/finalpjt/hraccoon/domain/approval/service/ApprovalService.java
Labels: Backend

#17 [#15] 결재자 이름 반환, 예외처리 메시지 수정
  src/main/java/org/finalpjt/hraccoon/domain/approval/constant/ApprovalMessageConstants.java
  src/main/java/org/finalpjt/hraccoon/domain/approval/data/dto/response/ApprovalResponse.java
  src/main/java/org/finalpjt/hraccoon/domain/approval/service/ApprovalService.java
Labels: bug, Backend, refactor

#18 [#16] 결재자 이름 반환
  src/main/java/org/finalpjt/hraccoon/domain/approval/service/ApprovalService.java
  src/main/java/org/finalpjt/hraccoon/domain/seat/constant/SeatMessageConstants.java
  src/main/java/org/finalpjt/hraccoon/domain/seat/service/SeatService.java
Labels: bug, Backend, refactor

#20 [#17] 좌석 api 수정
  src/main/java/org/finalpjt/hraccoon/domain/approval/ctrl/ApprovalController.java
  src/main/java/org/finalpjt/hraccoon/domain/approval/data/entity/Approval.java
  src/main/java/org/finalpjt/hraccoon/domain/approval/data/entity/ApprovalDetail.java
  src/main/java/org/finalpjt/hraccoon/domain/seat/ctrl/SeatController.java
Labels: Backend, refactor

#15 [#13] 직원 정보 단건 조회 기능 추가
  src/main/java/org/finalpjt/hraccoon/domain/seat/constant/SeatMessageConstants.java
  src/main/java/org/finalpjt/hraccoon/domain/seat/ctrl/SeatController.java
  src/main/java/org/finalpjt/hraccoon/domain/seat/data/dto/SeatUsingUserResponse.java
  src/main/java/org/finalpjt/hraccoon/domain/seat/data/dto/UserUsingSeatResponse.java
  src/main/java/org/finalpjt/hraccoon/domain/seat/repository/SeatStatusRepository.java
  src/main/java/org/finalpjt/hraccoon/domain/seat/service/SeatService.java
  src/main/resources/application.yml
Labels: enhancement, Backend, refactor

#22 [#19] 전체 좌석 조회 기능 추가
  src/main/java/org/finalpjt/hraccoon/domain/approval/constant/ApprovalMessageConstants.java
  src/main/java/org/finalpjt/hraccoon/domain/approval/data/dto/request/ApprovalRequest.java
  src/main/java/org/finalpjt/hraccoon/domain/approval/repository/ApprovalRepository.java
  src/main/java/org/finalpjt/hraccoon/domain/approval/service/ApprovalService.java
  src/main/java/org/finalpjt/hraccoon/domain/seat/constant/SeatMessageConstants.java
  src/main/java/org/finalpjt/hraccoon/domain/seat/ctrl/SeatController.java
  src/main/java/org/finalpjt/hraccoon/domain/seat/data/entity/Seat.java
  src/main/java/org/finalpjt/hraccoon/domain/seat/repository/SeatStatusRepository.java
  src/main/java/org/finalpjt/hraccoon/domain/seat/service/SeatService.java
Labels: enhancement, Backend

#21 [#18] 근태 기능 구현
  src/main/java/org/finalpjt/hraccoon/config/SecurityConfig.java
  src/main/java/org/finalpjt/hraccoon/domain/approval/service/ApprovalService.java
  src/main/java/org/finalpjt/hraccoon/domain/attendance/data/dto/response/AttendanceResponseDTO.java
  src/main/java/org/finalpjt/hraccoon/domain/attendance/data/entity/Attendance.java
  src/main/java/org/finalpjt/hraccoon/domain/attendance/service/AttendanceService.java
Labels: bug, Backend

#26 [#24] SeatOfficeFloorResponse userId 및 seat, seatStatus data 추가
  src/main/java/org/finalpjt/hraccoon/domain/seat/ctrl/SeatController.java
  src/main/java/org/finalpjt/hraccoon/domain/seat/data/dto/SeatOfficeFloorResponse.java
  src/main/java/org/finalpjt/hraccoon/domain/seat/service/SeatService.java
  src/main/resources/database/init-data.sql
Labels: bug, Backend

#27 [#25] 모든 좌석 확인 seatOffice code로 받아오기
  src/main/java/org/finalpjt/hraccoon/domain/seat/service/SeatService.java
Labels: Backend, refactor

#24 [#28] 좌석 충돌 해결
  src/main/java/org/finalpjt/hraccoon/domain/approval/constant/ApprovalMessageConstants.java
  src/main/java/org/finalpjt/hraccoon/domain/approval/ctrl/ApprovalController.java
  src/main/java/org/finalpjt/hraccoon/domain/approval/data/entity/Approval.java
  src/main/java/org/finalpjt/hraccoon/domain/approval/repository/ApprovalRepository.java
  src/main/java/org/finalpjt/hraccoon/domain/approval/service/ApprovalService.java
  src/main/java/org/finalpjt/hraccoon/domain/seat/config/SeatConfig.java
  src/main/java/org/finalpjt/hraccoon/domain/seat/repository/SeatStatusRepository.java
  src/main/java/org/finalpjt/hraccoon/domain/seat/service/SeatService.java
  src/test/java/org/finalpjt/hraccoon/domain/approval/service/ApprovalServiceTest.java
  src/test/java/org/finalpjt/hraccoon/domain/seat/service/SeatServiceTest.java
  src/test/resources/application.yml
Labels: Backend

#28 [#26] UserServiceTest, SeatServiceTest, TodoServiceTest, AuthServiceTest 테스트 코드 작성
  src/main/java/org/finalpjt/hraccoon/domain/auth/service/AuthService.java
  src/main/java/org/finalpjt/hraccoon/domain/code/data/entity/Code.java
  src/main/java/org/finalpjt/hraccoon/domain/seat/data/dto/SeatUsingUserResponse.java
  src/main/java/org/finalpjt/hraccoon/domain/seat/service/SeatService.java
  src/main/java/org/finalpjt/hraccoon/domain/todo/data/dto/TodoRequestDTO.java
  src/main/java/org/finalpjt/hraccoon/domain/user/constant/UserMessageConstants.java
  src/main/java/org/finalpjt/hraccoon/domain/user/data/dto/request/AbilityRequest.java
  src/main/java/org/finalpjt/hraccoon/domain/user/data/dto/request/UserInfoRequest.java
  src/main/java/org/finalpjt/hraccoon/domain/user/data/dto/request/UserRequest.java
  src/main/java/org/finalpjt/hraccoon/domain/user/service/UserService.java
  src/main/resources/application.yml
  src/test/java/org/finalpjt/hraccoon/domain/auth/service/AuthServiceTest.java
  src/test/java/org/finalpjt/hraccoon/domain/seat/service/SeatServiceTest.java
  src/test/java/org/finalpjt/hraccoon/domain/todo/service/TodoServiceTest.java
  src/test/java/org/finalpjt/hraccoon/domain/user/service/UserServiceTest.java
Labels: Backend

#30 [#28] Admin 기능 추가 및 userDetail 수정 및 테스트 코드 수정
  src/main/java/org/finalpjt/hraccoon/domain/auth/service/AuthService.java
  src/main/java/org/finalpjt/hraccoon/domain/user/constant/UserMessageConstants.java
  src/main/java/org/finalpjt/hraccoon/domain/user/ctrl/AdminController.java
  src/main/java/org/finalpjt/hraccoon/domain/user/ctrl/UserController.java
  src/main/java/org/finalpjt/hraccoon/domain/user/data/dto/request/AdminUserRequest.java
  src/main/java/org/finalpjt/hraccoon/domain/user/data/dto/request/UserDeleteRequest.java
  src/main/java/org/finalpjt/hraccoon/domain/user/data/dto/response/AdminUserResponse.java
  src/main/java/org/finalpjt/hraccoon/domain/user/data/entity/User.java
  src/main/java/org/finalpjt/hraccoon/domain/user/data/entity/UserDetail.java
  src/main/java/org/finalpjt/hraccoon/domain/user/repository/AbilityRepository.java
  src/main/java/org/finalpjt/hraccoon/domain/user/sepecification/UserSpecification.java
  src/main/java/org/finalpjt/hraccoon/domain/user/service/AdminService.java
  src/main/java/org/finalpjt/hraccoon/domain/user/service/UserService.java
  src/test/java/org/finalpjt/hraccoon/domain/auth/service/AuthServiceTest.java
  src/test/java/org/finalpjt/hraccoon/domain/todo/service/TodoServiceTest.java
  src/test/java/org/finalpjt/hraccoon/domain/user/service/AdminServiceTest.java
  src/test/java/org/finalpjt/hraccoon/domain/user/service/UserServiceTest.java
Labels: bug, enhancement, Backend

#31 [#29] (Batch) 출퇴근 기록 자동 기록, 수정, 삭제
  build.gradle
  src/main/java/org/finalpjt/hraccoon/HraccoonApplication.java
  src/main/java/org/finalpjt/hraccoon/batch/BatchConfig.java
  src/main/java/org/finalpjt/hraccoon/batch/BatchScheduler.java
  src/main/java/org/finalpjt/hraccoon/batch/RunIdIncrementer.java
  src/main/java/org/finalpjt/hraccoon/domain/attendance/data/entity/Attendance.java
  src/main/java/org/finalpjt/hraccoon/domain/attendance/repository/AttendanceRepository.java
  src/main/java/org/finalpjt/hraccoon/domain/attendance/service/AttendanceService.java
Labels: enhancement, Backend

#33 [#31] Test code 수정 및 BaseTimeEntity 추가
  src/main/java/org/finalpjt/hraccoon/domain/todo/data/entity/Todo.java
  src/main/java/org/finalpjt/hraccoon/domain/user/constant/UserMessageConstants.java
  src/main/java/org/finalpjt/hraccoon/domain/user/data/entity/Ability.java
  src/main/java/org/finalpjt/hraccoon/domain/user/data/entity/UserDetail.java
  src/main/java/org/finalpjt/hraccoon/domain/user/repository/UserRepository.java
  src/main/java/org/finalpjt/hraccoon/domain/user/service/AdminService.java
  src/main/java/org/finalpjt/hraccoon/domain/user/service/UserService.java
  src/test/java/org/finalpjt/hraccoon/domain/seat/service/SeatServiceTest.java
  src/test/java/org/finalpjt/hraccoon/domain/user/service/AdminServiceTest.java
  src/test/java/org/finalpjt/hraccoon/domain/user/service/UserServiceTest.java
  src/test/resources/application.yml
Labels: Backend, refactor

#35 [#32] Dockerfile 추가
  Dockerfile
Labels: cicd

#39 [#36] 관리자 직원 검색 퇴사여부 필터링 추가 및 중복 예외 처리
  src/main/java/org/finalpjt/hraccoon/domain/user/constant/UserMessageConstants.java
  src/main/java/org/finalpjt/hraccoon/domain/user/ctrl/AdminController.java
  src/main/java/org/finalpjt/hraccoon/domain/user/ctrl/UserController.java
  src/main/java/org/finalpjt/hraccoon/domain/user/data/dto/request/UserRequest.java
  src/main/java/org/finalpjt/hraccoon/domain/user/data/dto/response/UserSearchResponse.java
  src/main/java/org/finalpjt/hraccoon/domain/user/repository/AbilityRepository.java
  src/main/java/org/finalpjt/hraccoon/domain/user/repository/UserRepository.java
  src/main/java/org/finalpjt/hraccoon/domain/user/sepecification/UserSpecification.java
  src/main/java/org/finalpjt/hraccoon/domain/user/service/AdminService.java
  src/main/resources/database/init-data.sql
  src/test/java/org/finalpjt/hraccoon/domain/user/service/AdminServiceTest.java
Labels: Backend, refactor

#41 [#37] 직원 생성 시, 팀과 직위 바뀌는 오류 수정
  src/main/java/org/finalpjt/hraccoon/domain/user/service/AdminService.java
Labels: bug, Backend

#43 [BUILD] Deploy to main ver 0.0.3
  src/main/java/org/finalpjt/hraccoon/domain/user/ctrl/AdminController.java
  src/main/java/org/finalpjt/hraccoon/domain/user/data/dto/request/UserRequest.java
  src/main/java/org/finalpjt/hraccoon/domain/user/data/dto/response/UserResponse.java
  src/main/java/org/finalpjt/hraccoon/domain/user/data/entity/User.java
  src/main/java/org/finalpjt/hraccoon/domain/user/repository/UserRepository.java
  src/main/java/org/finalpjt/hraccoon/domain/user/service/AdminService.java
Labels: cicd
